### ISSUE TITLE
Placeholders stoped working when updated server version from 1.19 to 1.19.2

### ISSUE THREAD

**Issue by raimkras97** [wikmor/LPC#23]
upgrading server version from 1.19 to 1.19.2 placeholders get broken and this is what happens in console and in game this is what happens.
It may have something to do with the chat reporting 
Plugins that are used with LPC and all are at latest version:
1. ItemsAdder
2. TAB (by NEZNAMY)
3. DiscordSRV
4. PlaceholdersAPI
Also i checked ItemsAdder plugin's placeholders with PlaceholdersAPI and yes they show correctly

Server version: git-Paper-166 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

In game:
https://i.imgur.com/0aUdg3U.png

on console:
https://i.imgur.com/KAq77Qf.png

**Comment by raimkras97** [comment]
apparently its tab plugins fault

**Comment by haroldrc** [comment]
same problem
